CREATE DATABASE IF NOT EXISTS garage;


CREATE TABLE garage.vehicle ( 
id BIGINT(20) NOT NULL AUTO_INCREMENT,
type VARCHAR(255) NOT NULL,
color VARCHAR(255) DEFAULT NULL,
model VARCHAR(255) DEFAULT NULL,
numWheels INT DEFAULT NULL,
PRIMARY KEY (id) 
);

CREATE TABLE garage.car (
id BIGINT(20) NOT NULL,
plate VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (`id`)
);

CREATE TABLE garage.motorbike (
id BIGINT(20) NOT NULL,
plate VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (`id`)
);

CREATE TABLE garage.bicycle (
id BIGINT(20) NOT NULL,
PRIMARY KEY (`id`)
);
